### ISSUE TITLE
Fix linting

### ISSUE THREAD

**Issue by bplaster** [AraBlocks/ara-module-template#27]
## Expected Behavior
Linting passes

## Actual Behavior
Linting fails, and doesn't seem to catch shipright.js linting errors

## Steps to Reproduce the Problem

  1. npm run lint
  2.
  3.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by vipyne** [comment]
This is on Windows platform? @bplaster

**Comment by madelinecameron** [comment]
I believe this is fixed (95853c8bd83ec12bcfac112df4174fb680f28a5d). The issue was that eslint was reading `docs/scripts/*.js` so I added them to ignore since everything in docs/ is generated. 

I couldn't get it to trigger linting errors for shipright.

**Comment by bplaster** [comment]
This is on mac. Oh, we're just ignoring shipright linting?

**Comment by madelinecameron** [comment]
Nope, Shipright is in `scripts/`, the offending scripts were in `docs/scripts/` which are auto-generated. 

I couldn't get any errors from linting here, but definitely point me to the project that is throwing the linting errors and I'll fix the linting errors. :)

**Comment by madelinecameron** [comment]
OH. I know why it isn't being read in ara-module-template. One sec. :sweat_smile:

**Comment by madelinecameron** [comment]
(The `scripts/**/*.js` ignore was from when we didn't produce the scripts in scripts/. Those scripts are no longer in there. But also, it wouldn't pick up shipright if it didn't end in .js so double-edged)
